#!/usr/bin/env python

import os
import sys
from roslaunch.rlutil import get_or_generate_uuid

if __name__ == '__main__':
    get_or_generate_uuid(None, True)
    args = sys.argv
    args[0] = os.environ['VSCODE_ROS_DEBUG_DEBUGGER']
    os.execvp(args[0], args)
