services:
  - xvfb

language: node_js
node_js:
  - "10"

install:
  - npm install -g --silent gulp-cli

script:
  - npm install
  - npm run compile
  - npm run lint
  - gulp cover:enable
  - npm run test
  - npm run coveralls
